# Generated by Django 6.0 on 2025-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Komputer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brend", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="komputer/")),
                ("desc", models.TextField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField()),
                ("xotira", models.CharField(max_length=50)),
                ("ram", models.CharField(max_length=50)),
                ("ekran_olchami", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
